    FROM node:20 AS builder

    WORKDIR /app
    
    COPY package.json yarn.lock ./
    RUN yarn install --frozen-lockfile
    
    COPY . .
    RUN yarn build
    
    FROM node:20
    
    WORKDIR /app
    
    COPY package.json yarn.lock ./
    RUN yarn install --frozen-lockfile --production
    
    COPY --from=builder /app/dist ./dist
    
    CMD ["node", "dist/main.js"]
    